#!/bin/sh

# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
# Gradle start up script for POSIX generated by Gradle.
#
# Important for running:
#
# (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#     not POSIX compliant, but you have some other compliant shell such as
#     bash or ksh, you may want to edit this file.
#
# (2) Avoid modifying this script unless you need to further customize it in
#     order to reuse it in multiple locations.
#
# You will normally want to remove the option .
#     [Optional] Add a .jvmopts file in the same directory as gradle.properties
#     to override the default JVM options (ignored by gradlew.cmd).
#     See https://gradle.org/docs/current/userguide/java_build_platform.html#using_java_toolchains
# in the Gradle documentation.
#
# When using the Gradle wrapper, you can be confident that the correct
# Gradle version is used throughout your build, since the wrapper explicitly
# downloads and caches it before applying it to your build.
#
# Stop when "run using unzip" detection was created
if [ -z "$1" ] ; then
    has_args=false
else
    has_args=true
fi

##############################################################################
# Determine the Java command to use to start the JVM.
##############################################################################
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$msys" ] ; then
    case $OSTYPE in
        cygwin* | msys* | win32*)
            # Exit now for Windows
            break
            ;;
        *)
            # For non windows shells
            noprocess=$(ulimit -n)
            if [ "$?" -eq 0 ] ; then
                if [ "$noprocess" != 'unlimited' ] ; then
                    MAX_FD=$noprocess
                    if [ "$MAX_FD" -lt 4096 ] ; then
                        PRG="$0"
                        # Use the maximum available, or 32maximum if we can.
                        while IFS=: read -r check do
                            [ -z "$check" ] && continue
                            cmd="$check 2>/dev/null"
                            M=$cmd
                            [ -n "$M" ] && MAX_FD=$M && break
                        done <<< "$(ulimit -H -n 2>/dev/null | tr -d '\r' ; echo 'ulimit -n 2>/dev/null | tr -d '"'\r'"'
                    fi
                fi
            fi
            ;;
    esac
fi

# For Darwin, add options to specify how the application appears in the dock
if $darwin; then
    GRADLE_OPTS="$GRADLE_OPTS \"-Xdock:name=$APP_NAME\" \"-Xdock:icon=$APP_HOME/media/gradle.icns\""
fi

# For Cygwin or MSYS, switch paths to Windows format before running java
if { $cygwin || $msys; } && [[ "$1" == -* ]] ; then
    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    i=0
    for arg in "$@" ; do
        CHECK="$arg"
        CHECK2=`cygpath --unix "$CHECK" 2>/dev/null`
        TEST_CHECK_2=$?
        CHECK3=`expr "$CHECK" : '[^=]*=\(.*\)'`
        if (( $TEST_CHECK_2 == 0 )) && [[ "$CHECK" == "=" ]] ; then
            new_arg="`cygpath --path --windows "$CHECK2"`"
        elif (( $TEST_CHECK_2 == 0 )) ; then
            new_arg="`cygpath --path --windows "$CHECK2"`"
        elif test "x$CHECK3" != x ; then
            gcc_exec_prefix=`expr "$CHECK" : '[^=]*=\(.*\)'`
            new_arg="${CHECK%=*}=`cygpath --path --windows "$gcc_exec_prefix"`"
        else
            new_arg="`cygpath --windows "$CHECK"`"
        fi
        if [[ "${arg:0:1}" == "-" ]] ; then
            new_arg="-${new_arg}"
        fi
        eval "args[i]=\"$new_arg\""
        i=$((i+1))
    done
    set -- "${args[@]}"
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if { $cygwin || $msys; } && [[ -z "$1" ]] ; then
    CLASSPATH=`cygpath --path --windows "$CLASSPATH"`
fi

# Parses a version string back into major, minor, micro
parse_version() {
  VERSION_PART=$1
  MAJOR="${VERSION_PART%%.*}"
  VERSION_PART="${VERSION_PART#*.}"
  MINOR="${VERSION_PART%%.*}"
  VERSION_PART="${VERSION_PART#*.}"
  MICRO="${VERSION_PART%%.*}"
}

if [[ -z "$JAVA_TOOL_OPTIONS" ]] ; then
  JVM_ARGS="$GRADLE_OPTS $JAVA_OPTS"
else
  JVM_ARGS="$JAVA_TOOL_OPTIONS $GRADLE_OPTS $JAVA_OPTS"
fi

# Escape application args
save () {
    for i do printf %s\\n "$i" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/'/" ; done
    echo " "
}
APP_ARGS=$(save "$@")

# Collect all arguments for the java command
set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$APP_ARGS"

set +e

max_rss() {
  # Do nothing on POSIX systems
  return 0
}

if $cygwin || $msys ; then
    TERM=${TERM:-vt100}
fi

# Run the Gradle wrapper
"$JAVACMD" "${JVM_ARGS[@]}" "$@"
exit $?