name: Build Android App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: "temurin"

    - name: Generate Gradle Wrapper
      run: gradle wrapper --gradle-version 8.9

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: gradle-${{ runner.os }}-${{ github.sha }}
        restore-keys: gradle-${{ runner.os }}-

    - name: Build APK
      run: ./gradlew assembleDebug